name: Build and push C program using docker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t vidhidubey/vidhirepo:${{ github.run_number }} .
          docker images
          docker push vidhidubey/vidhirepo:${{ github.run_number }}
